/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/instances/': RouteRecordInfo<'/instances/', '/instances', Record<never, never>, Record<never, never>>,
    '/instances/current': RouteRecordInfo<'/instances/current', '/instances/current', Record<never, never>, Record<never, never>>,
    '/instances/current/downloads': RouteRecordInfo<'/instances/current/downloads', '/instances/current/downloads', Record<never, never>, Record<never, never>>,
    '/instances/current/executables': RouteRecordInfo<'/instances/current/executables', '/instances/current/executables', Record<never, never>, Record<never, never>>,
    '/instances/current/mods': RouteRecordInfo<'/instances/current/mods', '/instances/current/mods', Record<never, never>, Record<never, never>>,
    '/instances/current/settings': RouteRecordInfo<'/instances/current/settings', '/instances/current/settings', Record<never, never>, Record<never, never>>,
    '/instances/new': RouteRecordInfo<'/instances/new', '/instances/new', Record<never, never>, Record<never, never>>,
  }
}
